## Programming Assignment 2
## Together, these functions cache the inverse of a matrix

## This function creates a matrix object that can cache its own inverse:

makeCacheMatrix <- function(x = matrix()){
  s <- NULL
  set <- function(y) {
    x <<- y
    s <<- NULL
  }
  get <- function() x
  setinverse <- function(inverse) s <<- inverse
  getinverse <- function() s
  list(set = set, get = get,
       setinverse = setinverse,
       getinverse = getinverse)
}

## This function computes the inverse of the matrix generated by 
## makeCacheMatrix(), or retrieves the inverse from the cache if 
## it has already been computed:

cacheSolve <- function(x, ...) {
  s <- x$getinverse()
  if(!is.null(s)) {
    message("getting cached data")
    return(s)
  }
  data <- x$get()
  s <- solve(data, ...)
  x$setinverse(s)
  s
}